let doneSteps=new Set(),errors=JSON.parse(localStorage.getItem('ewj_errors')||'[]');const dialogue="Hi! My name is Anna. What's your name? Hi, Anna. I'm John. Nice to meet you. Nice to meet you too. Where are you from? I'm from Spain. I live in Cartagena.";
function speak(t,r=.82){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='en-GB';u.rate=r;speechSynthesis.speak(u)}
function done(n){doneSteps.add(n);bar.style.width=(doneSteps.size*20)+'%';progressText.textContent='Progreso: '+doneSteps.size+' de 5 pasos'}
function addError(x){if(!errors.includes(x)){errors.unshift(x);localStorage.setItem('ewj_errors',JSON.stringify(errors));renderErrors()}}
function renderErrors(){errorsBox=errors;document.getElementById('errors').innerHTML=errors.length?errors.map(x=>'<div class="error">❌ '+x+'</div>').join(''):'<p>🎉 Todavía no tienes errores guardados.</p>'}
function recog(cb){let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return null;let r=new R();r.lang='en-GB';r.onresult=e=>cb(e.results[0][0].transcript);return r}
listenBtn.onclick=()=>{speak(dialogue);done(1)};slowBtn.onclick=()=>{speak(dialogue,.58);done(1)};questionBtn.onclick=()=>speak("What's your name?");modelBtn.onclick=()=>speak("My name is Jose. I'm from Spain.");
document.querySelectorAll('.option').forEach(b=>b.onclick=()=>{let f=document.getElementById('listenFeedback');f.style.display='block';if(b.dataset.a==='spain'){f.textContent='✅ Correct! John is from Spain.';f.className='feedback success';done(2)}else{f.innerHTML='❌ Not quite. John says: <b>I\'m from Spain.</b>';addError('Listening: practicar “I\'m from Spain”.')}});
speakBtn.onclick=()=>{let s=voiceStatus,f=voiceFeedback,r=recog(t=>{s.textContent='Has dicho: “'+t+'”';f.style.display='block';f.innerHTML=/name|my name|i'm/i.test(t)?'✅ Muy bien.':'Prueba: <b>My name is Jose.</b>';done(3)});if(!r){s.textContent='Reconocimiento de voz no disponible.';return}r.onstart=()=>s.textContent='🎙️ Habla ahora...';r.onerror=()=>s.textContent='No he podido reconocerte. Inténtalo otra vez.';r.start()};
checkConversation.onclick=()=>{let t=conversation.value.toLowerCase(),f=conversationFeedback;f.style.display='block';if(t.includes('from')||t.includes('spain')){f.textContent='✅ Muy bien. Respuesta correcta.';f.className='feedback success';done(4)}else{f.innerHTML='⚠️ Prueba con: <b>I\'m from Spain.</b>';addError('Conversation: practicar “I\'m from + country”.')}};
repeatSpeakBtn.onclick=()=>{let f=repeatFeedback,r=recog(t=>{f.style.display='block';if(/name/.test(t)&&/from/.test(t)){f.textContent='🎉 Excellent! Lección 1 completada.';f.className='feedback success';done(5)}else{f.innerHTML='Buen intento. Repite: <b>My name is Jose. I\'m from Spain.</b>';addError('Repetición: practicar la presentación completa.')});if(r)r.start()};
clearErrors.onclick=()=>{errors=[];localStorage.removeItem('ewj_errors');renderErrors()};renderErrors();